services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - routes:/app/routes
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

volumes:
  routes:
