services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-json-ui
    ports:
      - "${FLASK_PORT:-5000}:5000"
    volumes:
      - .:/app
      - routes_local:/app/routes
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

volumes:
  routes_local:
