name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t flask-json-ui:latest -f Dockerfile .

      - name: Tag and push Docker image
        run: |
          docker tag flask-json-ui:latest ghcr.io/networkpaul/json-route-app/flask-json-ui:latest
          docker push ghcr.io/networkpaul/json-route-app/flask-json-ui:latest
