name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          # Build the Docker image using docker-compose.prod.yml
          docker-compose -f docker-compose.prod.yml build

          # Tag and push the Docker image
          docker tag flask-json-ui:latest ghcr.io/${{ github.repository }}/flask-json-ui:latest
          docker push ghcr.io/${{ github.repository }}/flask-json-ui:latest
